### ISSUE TITLE
DiscoverX on hive Catalog

### ISSUE THREAD

**Issue by SomanathSankaran** [databrickslabs/discoverx#47]
Is it possible to have discoverx run on non-unity catalog based databricks workspace based on hive metastore

**Comment by edurdevic** [comment]
Thank you for your question @SomanathSankaran.

At the moment it is not possible because we use the system tables that are only available for Unity Catalog tables.
In general, the other features on the roadmap are also dependent on Unity Catalog information. In some cases it would be theoretically possible to infer the same information from Hive tables, but that would be much slower.

We will keep this issue open to collect the interest on this functionality.

**Comment by SomanathSankaran** [comment]
hi @edurdevic  thanks for responding but I highly beleive if just for system tables we are leveraging UC, we can achieve the same using spark.catalog API and gather the necessary info if possible as discoverX will solve lot of GDPR related issue in datalake

**Comment by edurdevic** [comment]
For now this is indeed the case, but we are working on more advanced features that leverage functionality that is not available in Hive. As soon as UC Tags will be generally available (currently in private preview) the search functionality will switch from using the scan result to using UC Tags, this because there will be also other ways to populate the tag fields (eg. via UI or other native tools).
We will also shortly leverage entity relationship and lineage metadata that are not available in Hive.
So at the moment we are focussing on getting the core functionality out and once we have completed it we can see which are the features that we can use to support with only spark.catalog APIs.

**Comment by nfx** [comment]
@SomanathSankaran please make sure you migrate to Unity Catalog first :)

**Comment by SomanathSankaran** [comment]
Closing this issue as Migration to UC is the only optino
